---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: jenkinsagent
  name: jenkinsagent
  namespace: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: jenkinsagent
  template:
    metadata:
      labels:
        k8s-app: jenkinsagent
        namespace: devops
        name: jenkinsagent
    spec:
      hostAliases:
        - ip: "10.0.39.37"
          hostnames:
            - "gitlab.idevops.site"
        - ip: "172.20.10.3"
          hostnames:
            - "sonar.idevops.site"
        - ip: "172.20.10.3"
          hostnames:
            - "nexus.idevops.site"
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /home/jenkins/workspace /home/jenkins/jenkins-build-cache"]
          volumeMounts:
            - name: jenkins-workspace
              mountPath: /home/jenkins/workspace
            - name: jenkins-build-cache
              mountPath: /home/jenkins/jenkins-build-cache
      containers:
        - name: jenkinsagent
          image: jenkins/inbound-agent:latest-jdk17
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local:8080
            - name: JENKINS_SECRET
              value: dc2ad54d811b7c2cc406c4d4663dbf098f0bdf57799b45cfc0d6a75bc011370b
            - name: JENKINS_AGENT_NAME
              value: build
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/workspace
            - name: AGENT_WORKDIR
              value: /home/jenkins/workspace
          volumeMounts:
            - name: jenkins-build-cache
              mountPath: /home/jenkins/jenkins-build-cache
            - name: jenkins-workspace
              mountPath: /home/jenkins/workspace
      volumes:
        - name: jenkins-build-cache
          persistentVolumeClaim:
            claimName: jenkins-build-cache
        - name: jenkins-workspace
          persistentVolumeClaim:
            claimName: jenkins-workspace